### PR TITLE
Make ensemble's object and source fields public

### PR DESCRIPTION
**Pull request by wilsonbb**
Make `Ensemble._source` and `Ensemble._object` public fields (`Ensemble.source` and `Ensemble.object` respectively).

As this is simply a renaming, no new testing is added.

### CODE REVIEW

**Comment by wilsonbb** [comment]
@hombit I have also added you a reviewer to give you a way to signal whether you are ready to break the current API with this change.

**Review by hombit — APPROVED** [review]
Looks good to me! The only discussion point I have is protection of `.source`/`.object` attributes from being accidentally re-assigned by user with `ens.source = something`. We can make it work using "defensive shallow copy" pattern (I'm pretty sure that it has a better name =)
```python
class Ensemble:
    _object
    @property
    def object(self):
        # Will Dask make a shallow copy here? Could we make it read-only?
        return object.copy()
```

**Comment by hombit** [comment]
It actually doesn't solve #214, because that one was about `._time_col`, `._flux_col`, etc

**Review by dougbrn — APPROVED** [review]
looks good to me!

**Comment by dougbrn** [comment]
We'll get this from the refactor, correct? Is there a need to keep this open @wilsonbb ?

**Comment by wilsonbb** [comment]
> We'll get this from the refactor, correct? Is there a need to keep this open @wilsonbb ?

Yeah this is correct, closing.

**Pull request closed without merging**
